export const albums = {
  jovan: [
    {
      title: "DAMN.",
      artist: "Kendrick Lamar",
      cover:
        "https://t2.genius.com/unsafe/847x0/https%3A%2F%2Fimages.genius.com%2Ff3f77222e1b615e0a10354ea6282ff22.1000x1000x1.png",
      avg: 9.19,
      songs: [
        { title: "BLOOD.", rating: 9.0, placement: "none" },
        { title: "DNA.", rating: 9.8, placement: "none" },
        { title: "YAH.", rating: 7.0, placement: "none" },
        { title: "ELEMENT.", rating: 8.0, placement: "none" },
        { title: "FEEL.", rating: 9.0, placement: "none" },
        { title: "LOYALTY.", rating: 8.5, placement: "none" },
        { title: "PRIDE", rating: 10.0, placement: "2nd" },
        { title: "HUMBLE.", rating: 9.5, placement: "none" },
        { title: "LUST.", rating: 9.2, placement: "none" },
        { title: "LOVE.", rating: 9.0, placement: "none" },
        { title: "XXX.", rating: 10.0, placement: "none" },
        { title: "FEAR.", rating: 10.0, placement: "1st" },
        { title: "GOD.", rating: 7.0, placement: "none" },
        { title: "DUCKWORTH.", rating: 10.0, placement: "3rd" },
      ],
    },
    {
      title: "untitled unmastered.",
      artist: "Kendrick Lamar",
      cover:
        "https://t2.genius.com/unsafe/847x0/https%3A%2F%2Fimages.genius.com%2F539168707d36a67a51a4c1ed8a9d32c3.1000x1000x1.jpg",
      avg: 8.8,
      songs: [
        { title: "untitled 01 | 08.19.2014.", rating: 7.5, placement: "none" },
        { title: "untitled 02 | 06.23.2014.", rating: 9.0, placement: "none" },
        { title: "untitled 03 | 05.28.2013.", rating: 9.3, placement: "3rd" },
        { title: "untitled 04 | 08.14.2014.", rating: 8.5, placement: "none" },
        { title: "untitled 05 | 09.21.2014.", rating: 9.8, placement: "1st" },
        { title: "untitled 06 | 06.30.2014.", rating: 8.5, placement: "none" },
        { title: "untitled 07 | 2014 - 2016", rating: 8.0, placement: "none" },
        { title: "untitled 08 | 09.06.2014.", rating: 9.3, placement: "2nd" },
      ],
    },
    {
      title: "To Pimp A Butterfly",
      artist: "Kendrick Lamar",
      cover:
        "https://t2.genius.com/unsafe/847x0/https%3A%2F%2Fimages.genius.com%2Fde919556998a79d8ebfe51b9963121d1.1000x1000x1.png",
      avg: 9.54,
      songs: [
        { title: "Wesley's Theory", rating: 9.7, placement: "none" },
        { title: "For Free? - Interlude", rating: 9.0, placement: "none" },
        { title: "King Kunta", rating: 10.0, placement: "none" },
        { title: "Institutionalized", rating: 10.0, placement: "1st" },
        { title: "These Walls", rating: 10.0, placement: "3rd" },
        { title: "u", rating: 10.0, placement: "2nd" },
        { title: "Alright", rating: 9.8, placement: "none" },
        { title: "For Sale? - Interlude", rating: 9.2, placement: "none" },
        { title: "Momma", rating: 8.5, placement: "none" },
        { title: "Hood Politics", rating: 8.0, placement: "none" },
        { title: "How Much A Dollar Cost", rating: 10.0, placement: "none" },
        { title: "Complexion (A Zulu Love)", rating: 9.2, placement: "none" },
        { title: "The Blacker The Berry", rating: 9.6, placement: "none" },
        {
          title: "You Ain't Gotta Lie (Momma Said)",
          rating: 10.0,
          placement: "none",
        },
        { title: "i", rating: 9.8, placement: "none" },
        { title: "Mortal Man", rating: 10.0, placement: "none" },
      ],
    },
    {
      title: "good kid, m.A.A.d city",
      artist: "Kendrick Lamar",
      cover:
        "https://t2.genius.com/unsafe/344x344/https%3A%2F%2Fimages.genius.com%2Fb4d6d87f080c362200ce55ed35ec65bb.1000x1000x1.png",
      avg: 9.58,
      songs: [
        {
          title: "Sharane a.k.a Master Splinter's Daughter",
          rating: 9.5,
          placement: "none",
        },
        { title: "Bitch, Don't Kill My Vibe", rating: 9.4, placement: "none" },
        { title: "Backseat Freestyle", rating: 8.5, placement: "none" },
        { title: "The Art of Peer Pressure", rating: 10.0, placement: "3rd" },
        { title: "Money Trees", rating: 9.7, placement: "none" },
        { title: "Poetic Justice", rating: 9.5, placement: "none" },
        { title: "good kid", rating: 10.0, placement: "none" },
        { title: "m.A.A.d city", rating: 9.3, placement: "none" },
        { title: "Swimming Pools (Drank)", rating: 10.0, placement: "none" },
        {
          title: "Sing About Me, I'm Dying Of Thirst",
          rating: 10.1,
          placement: "1st",
        },
        { title: "Real", rating: 10.0, placement: "2nd" },
        { title: "Compton", rating: 8.5, placement: "none" },
      ],
    },
    {
      title: "channel ORANGE",
      artist: "Frank Ocean",
      cover:
        "https://t2.genius.com/unsafe/344x344/https%3A%2F%2Fimages.genius.com%2F6523ef2dbe975dd04570ee626edf53ca.1000x1000x1.png",
      avg: 9.01,
      songs: [
        { title: "Start", rating: 7.5, placement: "none" },
        { title: "Thinkin Bout You", rating: 9.7, placement: "none" },
        { title: "Fertilizer", rating: 8.0, placement: "none" },
        { title: "Sierra Leone", rating: 9.3, placement: "none" },
        { title: "Sweet Life", rating: 10.0, placement: "none" },
        { title: "Not Just Money", rating: 7.0, placement: "none" },
        { title: "Super Rich Kids", rating: 8.5, placement: "none" },
        { title: "Pilot Jones", rating: 8.7, placement: "none" },
        { title: "Crack Rock", rating: 9.2, placement: "none" },
        { title: "Pyramids", rating: 10.0, placement: "none" },
        { title: "Lost", rating: 9.4, placement: "none" },
        { title: "White", rating: 9.0, placement: "none" },
        { title: "Monks", rating: 9.5, placement: "none" },
        { title: "Bad Religion", rating: 10.0, placement: "none" },
        { title: "Pink Matter", rating: 10.0, placement: "none" },
        { title: "Forrest Gump", rating: 9.1, placement: "none" },
        { title: "End", rating: 8.0, placement: "none" },
      ],
    },
    {
      title: "Born Sinner",
      artist: "J. Cole",
      cover:
        "https://t2.genius.com/unsafe/847x0/https%3A%2F%2Fimages.genius.com%2Fcae5014446bde04b411c6fa684963ba8.592x592x1.webp",
      avg: 8.44,
      songs: [
        { title: "Villuminati", rating: 8.3, placement: "none" },
        { title: "Kerney Sermon - Skit", rating: 7.5, placement: "none" },
        { title: "Land Of The Snakes", rating: 8.2, placement: "none" },
        { title: "Power Trip", rating: 9.2, placement: "none" },
        { title: "No Money - Interlude", rating: 7.0, placement: "none" },
        { title: "Trouble", rating: 7.5, placement: "none" },
        { title: "Runaway", rating: 8.4, placement: "none" },
        { title: "She Knows", rating: 10.0, placement: "1st" },
        { title: "Rich Niggaz", rating: 8.3, placement: "none" },
        { title: "Where's Jerimaine? - Skit", rating: 8.0, placement: "none" },
        { title: "Forbidden Fruit", rating: 9.3, placement: "none" },
        { title: "Chaining Day", rating: 7.7, placement: "none" },
        {
          title: "Ain't That Some Shit - interlude",
          rating: 7.0,
          placement: "none",
        },
        { title: "Crooked Smile", rating: 9.5, placement: "3rd" },
        { title: "Let Nas Down", rating: 10.0, placement: "2nd" },
        { title: "Born Sinner", rating: 8.0, placement: "none" },
      ],
    },
    {
      title: "2014 Forrest Hills Drive",
      artist: "J. Cole",
      cover:
        "https://t2.genius.com/unsafe/344x344/https%3A%2F%2Fimages.genius.com%2F3b02f41397586e2b3c8bd3fbbc586928.1000x1000x1.png",
      avg: 9.03,
      songs: [
        { title: "Intro", rating: 7.5, placement: "none" },
        { title: "January 28th", rating: 9.7, placement: "none" },
        { title: "Wet Dreamz", rating: 10.0, placement: "3rd" },
        { title: "03' Adolesence", rating: 8.5, placement: "none" },
        { title: "A Tale Of 2 Citiez", rating: 8.0, placement: "none" },
        { title: "Fire Squad", rating: 8.7, placement: "none" },
        { title: "St. Tropez", rating: 8.8, placement: "none" },
        { title: "G.O.M.D", rating: 9.0, placement: "none" },
        { title: "No Role Modelz", rating: 10.0, placement: "2nd" },
        { title: "Hello", rating: 8.2, placement: "none" },
        { title: "Apperently", rating: 9.0, placement: "none" },
        { title: "Love Yourz", rating: 10.0, placement: "1st" },
        { title: "Note To Self", rating: 7.5, placement: "none" },
      ],
    },
  ],
  meli: [
    {
      title: "channel ORANGE",
      artist: "Frank Ocean",
      cover:
        "https://t2.genius.com/unsafe/344x344/https%3A%2F%2Fimages.genius.com%2F6523ef2dbe975dd04570ee626edf53ca.1000x1000x1.png",
      avg: 9.01,
      songs: [
        { title: "Start", rating: 7.5, placement: "none" },
        { title: "Thinkin Bout You", rating: 9.7, placement: "none" },
        { title: "Fertilizer", rating: 8.0, placement: "none" },
        { title: "Sierra Leone", rating: 9.3, placement: "none" },
        { title: "Sweet Life", rating: 10.0, placement: "none" },
        { title: "Not Just Money", rating: 7.0, placement: "none" },
        { title: "Super Rich Kids", rating: 8.5, placement: "none" },
        { title: "Pilot Jones", rating: 8.7, placement: "none" },
        { title: "Crack Rock", rating: 9.2, placement: "none" },
        { title: "Pyramids", rating: 10.0, placement: "none" },
        { title: "Lost", rating: 9.4, placement: "none" },
        { title: "White", rating: 9.0, placement: "none" },
        { title: "Monks", rating: 9.5, placement: "none" },
        { title: "Bad Religion", rating: 10.0, placement: "none" },
        { title: "Pink Matter", rating: 10.0, placement: "none" },
        { title: "Forrest Gump", rating: 9.1, placement: "none" },
        { title: "End", rating: 8.0, placement: "none" },
      ],
    },
  ],
};
